# SPDX-FileCopyrightText: 2017-2019 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: LGPL-3.0-only

image: elixir:1.7

variables:
  MIX_ENV: test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - deps
    - _build

stages:
  - test
  - publish

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix compile --force

lint:
  stage: test
  script:
    - mix format --check-formatted

unit-testing:
  stage: test
  coverage: '/(\d+\.\d+\%) \| Total/'
  script:
    - mix test --trace --preload-modules --cover

analysis:
  stage: test
  script:
    - mix credo --strict --only=warnings,todo,fixme,consistency,readability
